title: 제나 안 재나~
author: minddoi
email: minddoi493@gmail.com
description: 개발과 디자인을 좋아하는 대학생의 끄적임 공간
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: 제나 Jenna
  tagline: 디자인까지 잘하는 개발자를<br> 꿈꾸는 제나라고 합니다｡*⭒
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  search: true # set to true to enable searchbar
  dark_mode: true # set to true to add dark mode toggle
  portfolio_image: "assets/profile1.jpg" # the path from the base directory of the site to the image to display (no / at the start)
  html_lang: "en" # set the lang attribute of the <html> tag for the pages. See here for a list of codes: https://www.w3schools.com/tags/ref_country_codes.asp
  condensed_mobile:
    #- home
    - page
    - post
  # generate social links in footer
  social_links:
    #twitter: samarsault
    github:  minddoi
    #linkedIn: in/samarsault
    #dribbble: jekyll
    #flickr:   jekyll
    instagram: min_ddoi
    #pinterest: jekyll
    #youtube: jekyll
    #facebook: jekyll
    #soundcloud: jekyll
    #telegram: jekyll
    #gitlab: jekyll
    email: minddoi493@gmail.com

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: plainwhite

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
